"""
Analysis Plan–aware chart ordering hygiene (86I).

apply_analysis_plan_chart_hygiene() adjusts chart scores so that charts
covering target_metrics or important_dimensions surface first, while charts
whose columns are all in columns_to_ignore are down-ranked.

Rules (applied in order):
  1. Ignored-column penalty — charts whose all identified columns are in
     columns_to_ignore receive a ×0.40 score multiplier.
  2. Target × dimension boost (+1.5) — chart pairs a target metric with a
     dimension (the strongest business narrative).
  3. Target × time-series boost (+1.2) — trend of a target over a real date
     column.
  4. Target-only boost (+0.8) — histogram or scatter of a target metric.
  5. Dimension-only boost (+0.3) — bar or pie of an important dimension.

Charts with no identifiable column references (e.g. heatmaps using generic
keys) are left unchanged.

Safe fallbacks:
  - analysis_plan is None → charts returned unchanged.
  - analysis_plan.confidence < 0.6 (generic / ambiguous dataset) → unchanged.
  - No chart is deleted; ranking decides the final order.

Column name extraction:
  x_label and y_label reliably contain the raw column names for all chart
  types generated by the charting orchestrator:
    histogram   → x_label=col,      y_label="Count"
    scatter     → x_label=col1,     y_label=col2
    timeseries  → x_label=date_col, y_label=num_col
    cat bar     → x_label=col,      y_label="Count"
  Generic labels ("Count", "Frequency", etc.) are filtered before matching.
"""
from __future__ import annotations

from app.schemas.analysis_plan import AnalysisPlan

# ── Column-order prioritisation ───────────────────────────────────────────────

def prioritize_columns_for_charts(
    columns: list[str],
    analysis_plan: AnalysisPlan | None,
) -> list[str]:
    """Reorder columns so plan-relevant ones appear first within each budget slice.

    Ordering tiers (relative order within each tier is preserved):
      1. target_metrics
      2. important_dimensions (not also a target)
      3. all other non-ignored columns
      4. columns_to_ignore (last — least likely to be generated within budget)

    If analysis_plan is None or confidence < 0.6, columns are returned unchanged
    so the existing DataFrame-order behaviour is preserved.
    """
    if not analysis_plan or analysis_plan.confidence < 0.6:
        return columns

    col_set    = set(columns)
    target_set = set(analysis_plan.target_metrics)    & col_set
    dim_set    = set(analysis_plan.important_dimensions) & col_set - target_set
    ignore_set = set(analysis_plan.columns_to_ignore) & col_set

    targets = [c for c in columns if c in target_set]
    dims    = [c for c in columns if c in dim_set]
    others  = [c for c in columns if c not in target_set and c not in dim_set and c not in ignore_set]
    ignored = [c for c in columns if c in ignore_set]

    return targets + dims + others + ignored


# ── Score adjustments ─────────────────────────────────────────────────────────

_IGNORE_PENALTY       = 0.40  # ×score — same factor as finding hygiene
_TARGET_DIM_BOOST     = 1.5   # target × dimension — strongest business chart
_TARGET_TIME_BOOST    = 1.2   # target × real date col — trend chart
_TARGET_BOOST         = 0.8   # any chart showing a target metric
_DIM_BOOST            = 0.3   # any chart showing an important dimension

# Known placeholder labels that are NOT column names.
_GENERIC_LABELS: frozenset[str] = frozenset({
    "count", "frequency", "density", "value", "date", "label",
    "x", "y", "mean", "median", "percent", "index",
})


# ── Helpers ───────────────────────────────────────────────────────────────────

def _cols_from_chart(chart: dict) -> list[str]:
    """Extract actual column names referenced by a chart payload.

    x_label and y_label contain the raw column names for all built-in chart
    types.  Generic placeholder values are filtered out.
    """
    cols: list[str] = []
    for field in ("x_label", "y_label"):
        val = chart.get(field)
        if isinstance(val, str) and val and val.lower() not in _GENERIC_LABELS:
            cols.append(val)
    return list(dict.fromkeys(cols))  # deduplicate, preserve order


# ── Public API ────────────────────────────────────────────────────────────────

def apply_analysis_plan_chart_hygiene(
    charts: list[dict],
    analysis_plan: AnalysisPlan | None,
) -> list[dict]:
    """Adjust chart scores using analysis_plan context.

    Returns a new list of shallow-copied dicts sorted by score descending.
    Input list and dicts are not mutated.
    Safe to call with analysis_plan=None.
    """
    if not analysis_plan or analysis_plan.confidence < 0.6:
        return charts

    target_set = set(analysis_plan.target_metrics)
    dim_set    = set(analysis_plan.important_dimensions)
    time_set   = set(analysis_plan.time_columns)
    ignore_set = set(analysis_plan.columns_to_ignore)

    out: list[dict] = []
    for chart in charts:
        c    = dict(chart)           # shallow copy — do not mutate caller's dict
        cols = _cols_from_chart(c)

        # ── Ignored-column penalty ────────────────────────────────────────────
        if cols and all(col in ignore_set for col in cols):
            c["score"]               = float(c.get("score", 5.0)) * _IGNORE_PENALTY
            c["plan_penalty_reason"] = "ignored_column"
            out.append(c)
            continue

        # ── Plan-relevance boosts ─────────────────────────────────────────────
        if cols:
            has_target = any(col in target_set for col in cols)
            has_dim    = any(col in dim_set    for col in cols)
            has_time   = any(col in time_set   for col in cols)

            boost  = 0.0
            reason = None

            if has_target and has_dim:
                boost, reason = _TARGET_DIM_BOOST,  "target_metric_x_dimension"
            elif has_target and has_time:
                boost, reason = _TARGET_TIME_BOOST, "target_metric_trend"
            elif has_target:
                boost, reason = _TARGET_BOOST,      "target_metric"
            elif has_dim:
                boost, reason = _DIM_BOOST,         "important_dimension"

            if boost:
                c["score"]             = float(c.get("score", 5.0)) + boost
                c["plan_boost_reason"] = reason

        out.append(c)

    out.sort(key=lambda c: c.get("score", 0), reverse=True)
    return out
