from __future__ import annotations

from datetime import datetime

import pandas as pd

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0f172a; color: #e2e8f0; line-height: 1.6; padding: 2rem; }}
  .container {{ max-width: 1100px; margin: 0 auto; }}
  h1 {{ font-size: 2rem; font-weight: 700; color: #f8fafc; margin-bottom: 0.25rem; }}
  h2 {{ font-size: 1.25rem; font-weight: 600; color: #94a3b8; margin: 2rem 0 1rem; padding-bottom: 0.5rem; border-bottom: 1px solid #1e293b; }}
  h3 {{ font-size: 1rem; font-weight: 600; color: #cbd5e1; margin-bottom: 0.5rem; }}
  .header {{ margin-bottom: 2rem; }}
  .subtitle {{ color: #64748b; font-size: 0.875rem; margin-top: 0.25rem; }}
  .badge {{ display: inline-block; padding: 0.125rem 0.5rem; border-radius: 9999px; font-size: 0.75rem; font-weight: 600; }}
  .badge-green {{ background: #064e3b; color: #6ee7b7; }}
  .badge-yellow {{ background: #451a03; color: #fcd34d; }}
  .badge-red {{ background: #4c0519; color: #fca5a5; }}
  .badge-blue {{ background: #1e3a5f; color: #93c5fd; }}
  .badge-purple {{ background: #2e1065; color: #c4b5fd; }}
  .card {{ background: #1e293b; border: 1px solid #334155; border-radius: 0.75rem; padding: 1.5rem; margin-bottom: 1rem; }}
  .grid-2 {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }}
  .grid-4 {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 1rem; }}
  .stat-card {{ background: #1e293b; border: 1px solid #334155; border-radius: 0.5rem; padding: 1rem; text-align: center; }}
  .stat-value {{ font-size: 2rem; font-weight: 700; color: #6366f1; }}
  .stat-label {{ font-size: 0.75rem; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; }}
  .health-grade {{ font-size: 4rem; font-weight: 900; }}
  .grade-A {{ color: #10b981; }}
  .grade-B {{ color: #6366f1; }}
  .grade-C {{ color: #f59e0b; }}
  .grade-D {{ color: #ef4444; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.875rem; }}
  th {{ background: #0f172a; color: #94a3b8; font-weight: 600; padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid #334155; }}
  td {{ padding: 0.5rem 0.75rem; border-bottom: 1px solid #1e293b; color: #cbd5e1; }}
  tr:hover td {{ background: #0f172a20; }}
  .insight-card {{ background: #0f172a; border-left: 3px solid #6366f1; border-radius: 0 0.5rem 0.5rem 0; padding: 1rem; margin-bottom: 0.75rem; }}
  .insight-finding {{ font-weight: 600; color: #e2e8f0; margin-bottom: 0.25rem; }}
  .insight-evidence {{ font-size: 0.8rem; color: #94a3b8; margin-bottom: 0.25rem; }}
  .insight-action {{ font-size: 0.8rem; color: #6366f1; }}
  .narrative {{ color: #cbd5e1; line-height: 1.8; }}
  .narrative p {{ margin-bottom: 1rem; }}
  footer {{ margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #1e293b; color: #475569; font-size: 0.75rem; text-align: center; }}
  @media print {{ body {{ background: white; color: black; }} .card {{ border: 1px solid #ccc; background: #f9f9f9; }} }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>{title}</h1>
    <div class="subtitle">Generated on {date} &nbsp;·&nbsp; Powered by Analyst Pro</div>
  </div>

  <div class="grid-4">
    <div class="stat-card"><div class="stat-value">{n_rows}</div><div class="stat-label">Rows</div></div>
    <div class="stat-card"><div class="stat-value">{n_cols}</div><div class="stat-label">Columns</div></div>
    <div class="stat-card"><div class="stat-value">{missing_pct}%</div><div class="stat-label">Missing</div></div>
    <div class="stat-card"><div class="health-grade grade-{grade}">{grade}</div><div class="stat-label">Health Grade</div></div>
  </div>

  {narrative_section}

  <h2>Data Quality</h2>
  <div class="card">
    <table>
      <thead><tr><th>Dimension</th><th>Score</th><th>Status</th></tr></thead>
      <tbody>{quality_rows}</tbody>
    </table>
  </div>

  <h2>Column Profiles</h2>
  <div class="card">
    <table>
      <thead><tr><th>Column</th><th>Type</th><th>Missing%</th><th>Unique</th><th>Mean</th><th>Std</th><th>Status</th></tr></thead>
      <tbody>{column_rows}</tbody>
    </table>
  </div>

  <h2>Top Insights</h2>
  {insights_html}

  {cleaning_section}

  <footer>Report generated by Analyst Pro &nbsp;·&nbsp; {date}</footer>
</div>
</body>
</html>"""


def _grade(score: float) -> str:
    if score >= 80:
        return "A"
    if score >= 60:
        return "B"
    if score >= 40:
        return "C"
    return "D"


def _severity_badge(severity: str) -> str:
    color = {"high": "badge-red", "medium": "badge-yellow", "low": "badge-blue"}.get(
        str(severity).lower(), "badge-purple"
    )
    return f'<span class="badge {color}">{severity}</span>'


def generate_html_report(
    df: pd.DataFrame,
    analysis_result: dict,
    project_name: str = "Dataset Analysis",
) -> str:
    n_rows, n_cols = df.shape
    missing_pct = round(df.isnull().mean().mean() * 100, 1)

    health_score = analysis_result.get("health_score", 0)
    if isinstance(health_score, dict):
        health_score = health_score.get("overall", 0)
    health_score = float(health_score or 0)
    grade = _grade(health_score)

    # narrative
    narrative = analysis_result.get("narrative", "")
    if narrative:
        paras = [p.strip() for p in str(narrative).split("\n\n") if p.strip()]
        narrative_html = "".join(f"<p>{p}</p>" for p in paras)
        narrative_section = f'<h2>Executive Summary</h2><div class="card narrative">{narrative_html}</div>'
    else:
        narrative_section = ""

    # quality rows
    quality_data = analysis_result.get("health_breakdown", {})
    if not quality_data:
        quality_data = {
            "Completeness": health_score,
            "Consistency": health_score,
        }
    qrows = ""
    for dim, score in quality_data.items():
        sc = float(score) if isinstance(score, (int, float)) else 0
        badge_cls = "badge-green" if sc >= 80 else "badge-yellow" if sc >= 60 else "badge-red"
        qrows += f'<tr><td>{dim}</td><td>{sc:.0f}/100</td><td><span class="badge {badge_cls}">{"Good" if sc >= 80 else "Fair" if sc >= 60 else "Poor"}</span></td></tr>'

    # column profiles
    profile = analysis_result.get("profile", {})
    columns_data = profile.get("columns", []) if isinstance(profile, dict) else []
    crow = ""
    for col_info in columns_data[:50]:
        name = col_info.get("name", "")
        dtype = col_info.get("dtype", "")
        miss = col_info.get("missing_pct", 0)
        uniq = col_info.get("unique_count", col_info.get("n_unique", ""))
        mean = col_info.get("mean", "")
        std = col_info.get("std", "")
        mean_str = f"{mean:.2f}" if isinstance(mean, float) else (str(mean) if mean else "—")
        std_str = f"{std:.2f}" if isinstance(std, float) else (str(std) if std else "—")
        miss_f = float(miss) if miss else 0
        if miss_f > 30:
            status = '<span class="badge badge-red">High missing</span>'
        elif miss_f > 5:
            status = '<span class="badge badge-yellow">Some missing</span>'
        else:
            status = '<span class="badge badge-green">Good</span>'
        crow += f"<tr><td><strong>{name}</strong></td><td>{dtype}</td><td>{miss_f:.1f}%</td><td>{uniq}</td><td>{mean_str}</td><td>{std_str}</td><td>{status}</td></tr>"

    # insights
    insights = analysis_result.get("insights", [])
    insights_html = ""
    for ins in insights[:10]:
        finding = ins.get("finding", ins.get("title", ""))
        evidence = ins.get("evidence", "")
        action = ins.get("recommendation", ins.get("action", ""))
        severity = ins.get("severity", "medium")
        insights_html += f"""
        <div class="insight-card">
          <div class="insight-finding">{finding} {_severity_badge(severity)}</div>
          {'<div class="insight-evidence">' + str(evidence) + '</div>' if evidence else ''}
          {'<div class="insight-action">→ ' + str(action) + '</div>' if action else ''}
        </div>"""

    # cleaning section
    cleaning = analysis_result.get("cleaning_report", analysis_result.get("cleaning", []))
    if cleaning and isinstance(cleaning, list):
        c_rows = ""
        for step in cleaning[:20]:
            s = step.get("step", step.get("action", ""))
            d = step.get("detail", step.get("description", ""))
            imp = step.get("impact", "")
            c_rows += f"<tr><td>{s}</td><td>{d}</td><td>{imp}</td></tr>"
        cleaning_section = f'<h2>Cleaning Actions</h2><div class="card"><table><thead><tr><th>Step</th><th>Detail</th><th>Impact</th></tr></thead><tbody>{c_rows}</tbody></table></div>'
    else:
        cleaning_section = ""

    return _HTML_TEMPLATE.format(
        title=project_name,
        date=datetime.now().strftime("%Y-%m-%d %H:%M"),
        n_rows=f"{n_rows:,}",
        n_cols=n_cols,
        missing_pct=missing_pct,
        grade=grade,
        narrative_section=narrative_section,
        quality_rows=qrows,
        column_rows=crow,
        insights_html=insights_html,
        cleaning_section=cleaning_section,
    )


def generate_pdf_report(df: pd.DataFrame, analysis_result: dict, project_name: str = "Dataset Analysis") -> bytes:
    html = generate_html_report(df, analysis_result, project_name)
    try:
        import pdfkit
        return pdfkit.from_string(html, False)
    except ImportError:
        return html.encode("utf-8")
    except Exception:
        return html.encode("utf-8")


def generate_excel_report(
    df: pd.DataFrame,
    analysis_result: dict,
    project_name: str = "Dataset Analysis",
) -> bytes:
    """
    Generate a multi-sheet Excel workbook from an analysis result.
    Returns raw bytes suitable for an HTTP response.

    Sheets:
        1. Summary       — dataset stats + health score
        2. Insights      — all insights as a table
        3. Column Profiles — per-column statistics
        4. Cleaning Report — cleaning steps
        5. Data Preview  — first 200 rows of raw data
    """
    import io
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter

    DARK_FILL = PatternFill(start_color="1E293B", end_color="1E293B", fill_type="solid")
    HEADER_FONT = Font(bold=True, color="F8FAFC", size=11)
    TITLE_FONT = Font(bold=True, color="F8FAFC", size=14)
    NORMAL_FONT = Font(color="CBD5E1", size=10)
    THIN_BORDER = Border(
        bottom=Side(style="thin", color="334155"),
    )

    def _style_header_row(ws, row_num: int, ncols: int):
        for col in range(1, ncols + 1):
            cell = ws.cell(row=row_num, column=col)
            cell.fill = DARK_FILL
            cell.font = HEADER_FONT
            cell.alignment = Alignment(horizontal="left", vertical="center")
            cell.border = THIN_BORDER

    def _auto_width(ws, min_w: int = 10, max_w: int = 50):
        for col in ws.columns:
            max_len = max_w
            col_letter = get_column_letter(col[0].column)
            vals = [str(c.value or "") for c in col if c.value is not None]
            if vals:
                max_len = min(max(len(v) for v in vals) + 4, max_w)
                max_len = max(max_len, min_w)
            ws.column_dimensions[col_letter].width = max_len

    wb = Workbook()

    # ── Sheet 1: Summary ──────────────────────────────────────────────────────
    ws1 = wb.active
    ws1.title = "Summary"
    ws1.sheet_view.showGridLines = False

    ws1["A1"] = project_name
    ws1["A1"].font = TITLE_FONT
    ws1["A2"] = f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    ws1["A2"].font = Font(color="64748B", size=10, italic=True)

    summary = analysis_result.get("dataset_summary", {})
    health = analysis_result.get("health_score", {})

    headers = ["Metric", "Value"]
    ws1.append([])
    ws1.append(headers)
    _style_header_row(ws1, ws1.max_row, 2)

    stats = [
        ("Rows", summary.get("rows", "—")),
        ("Columns", summary.get("columns", "—")),
        ("Numeric Columns", summary.get("numeric_cols", "—")),
        ("Categorical Columns", summary.get("categorical_cols", "—")),
        ("Missing Data %", f"{summary.get('missing_pct', 0):.1f}%"),
        ("Health Score", f"{health.get('total', health.get('overall', '—'))}/100"),
    ]
    for label, val in stats:
        ws1.append([label, val])

    ws1.freeze_panes = "A5"
    _auto_width(ws1)

    # ── Sheet 2: Insights ─────────────────────────────────────────────────────
    ws2 = wb.create_sheet("Insights")
    ws2.sheet_view.showGridLines = False

    headers2 = ["#", "Type", "Severity", "Finding", "Evidence", "Action"]
    ws2.append(headers2)
    _style_header_row(ws2, 1, len(headers2))
    ws2.freeze_panes = "A2"

    insights = analysis_result.get("insights", [])
    for i, ins in enumerate(insights, 1):
        ws2.append([
            i,
            ins.get("type", ""),
            ins.get("severity", ""),
            ins.get("finding", ins.get("title", "")),
            ins.get("evidence", ""),
            ins.get("action", ""),
        ])

    _auto_width(ws2, max_w=60)

    # ── Sheet 3: Column Profiles ──────────────────────────────────────────────
    ws3 = wb.create_sheet("Column Profiles")
    ws3.sheet_view.showGridLines = False

    headers3 = ["Column", "Type", "Missing %", "Unique", "Mean", "Std", "Min", "Max"]
    ws3.append(headers3)
    _style_header_row(ws3, 1, len(headers3))
    ws3.freeze_panes = "A2"

    profile = analysis_result.get("profile", {})
    columns_profile = profile.get("columns", []) if isinstance(profile, dict) else []
    for col in columns_profile:
        ws3.append([
            col.get("name", ""),
            col.get("dtype", ""),
            f"{col.get('missing_pct', 0):.1f}%",
            col.get("unique_count", col.get("n_unique", "—")),
            round(col.get("mean", 0) or 0, 4) if col.get("mean") is not None else "—",
            round(col.get("std", 0) or 0, 4) if col.get("std") is not None else "—",
            col.get("min", "—"),
            col.get("max", "—"),
        ])

    _auto_width(ws3)

    # ── Sheet 4: Cleaning Report ──────────────────────────────────────────────
    ws4 = wb.create_sheet("Cleaning Report")
    ws4.sheet_view.showGridLines = False

    headers4 = ["Step", "Detail", "Impact"]
    ws4.append(headers4)
    _style_header_row(ws4, 1, len(headers4))
    ws4.freeze_panes = "A2"

    cleaning = analysis_result.get("cleaning_report", [])
    for item in cleaning:
        if isinstance(item, dict):
            ws4.append([item.get("step", ""), item.get("detail", ""), item.get("impact", "")])
        else:
            ws4.append([str(item), "", ""])

    _auto_width(ws4, max_w=60)

    # ── Sheet 5: Data Preview ─────────────────────────────────────────────────
    if not df.empty:
        ws5 = wb.create_sheet("Data Preview")
        ws5.sheet_view.showGridLines = False

        preview = df.head(200)
        ws5.append(list(preview.columns))
        _style_header_row(ws5, 1, len(preview.columns))
        ws5.freeze_panes = "A2"

        for _, row in preview.iterrows():
            ws5.append([str(v) if not isinstance(v, (int, float, type(None))) else v for v in row])

        _auto_width(ws5)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
