"""add_column_annotations_to_projects

Revision ID: 95df4ec3efa8
Revises: b562f8d6f803
Create Date: 2026-04-12 19:06:10.503890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95df4ec3efa8'
down_revision: Union[str, Sequence[str], None] = 'b562f8d6f803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('column_annotations_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'column_annotations_json')
    # ### end Alembic commands ###
